### ISSUE TITLE
Visual Studio Keymap references old GitHub repository on Visual Studio Marketplace

### ISSUE THREAD

**Issue by connorads** [microsoft/vscode-vs-keybindings#21]
Visual Studio Keymap references old GitHub repository on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vs-keybindings)

`rebornix/vscode-vs-keybindings` should be `microsoft/vscode-vs-keybindings`

![image](https://user-images.githubusercontent.com/10026538/61969755-2da10b80-afd3-11e9-8b37-abc34c396874.png)

**Comment by aberus** [comment]
This issue can be closed. Fixed with version 0.2.1
