### ISSUE TITLE
Is there a way to port VSCode's keyboard shortcuts to Visual Studio

### ISSUE THREAD

**Issue by QingGo** [microsoft/vscode-vs-keybindings#26]
I have used VSCode for a time and new to Visual Studio. VS shortcuts is very difference to VSCode. When I find if there are a way to use VSCode's  shortcuts in Visual Studio I find this repo. I wonder if there are a way to port VSCode's keyboard shortcuts to Visual Studio? Thanks!

**Comment by aberus** [comment]
Answered in another issue https://github.com/microsoft/vscode-vs-keybindings/issues/23#issuecomment-577680162

**Comment by QingGo** [comment]
Thank you! @aberus
