### ISSUE TITLE
Shift-option-arrow should select words on MacOS

### ISSUE THREAD

**Issue by natewaddoups** [microsoft/vscode-vs-keybindings#35]
Repro steps:

1. use a macbook
2. open some source code in Visual Studio Code (I'm using typescript, in case the type of code matters)
3. put the cursor on the left side of a word
4. press option-shift-right-arrow

**Expected result:** the entire word is selected.

**Actual result:** only one character is selected.

Word-by-word NAVIGATION works in VSC using option-arrow.

Word-by-word SELECTION works in this text-entry box (the UI that I'm using to submit this feedback right now in VSC) using option-shift-arrow.

The same hotkey also performs word selection in every other Mac app.

The same hotkey does NOT perform word selection in VSC's source-code editing window.

**Comment by natewaddoups** [comment]
This is not a VS Code bug after all, it was caused by the Visual Studio Keymap extension.

**Comment by gusalvestavo** [comment]
Good tip! For me, what broke it was the Notepad++ keymap extension.
